stack {
  name        = "spoke_networking2"
  description = "spoke_networking2"
  id          = "bba3ac42-af0d-49e3-890d-646279747877"
}

# In this case, we will import only the variables, that fits the main.tf
# The main.tf is NOT generated by Terramate

import {
  source = "/terramate/modules/network/variables.tm.hcl"
}